odoo:
  ports:
  - 88:8069/tcp
  environment:
    PGHOST: db
    PGPASSWORD: odoopass
    PGUSER: odoo
  tty: true
  image: docker-odoo:10.0
#  image: xtremxpert/docker-odoo:10.0
  links:
  - db:db
  stdin_open: true
  volumes:
  - /tmp/o10/extra-addons:/mnt/extra-addons
  - /tmp/o10/filestore:/var/lib/odoo/filestore
  - /tmp/o10/config:/etc/odoo
db:
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_PASSWORD: odoopass
    POSTGRES_USER: odoo
  tty: true
  image: postgres:9.6-alpine
  stdin_open: true
  volumes:
  - /tmp/o10/pgdata:/var/lib/postgresql/data/pgdata
pga:
    image: lunyuan/phppgadmin
    stdin_open: true
    tty: true
    links:
    - db:db
    ports:
    - 89:80