odoo:
  ports:
  - 80:8069/tcp
  environment:
    PGHOST: db
    PGPASSWORD: odoopass
    PGUSER: odoo
  tty: true
#  image: reg.portall.ca/reiva/docker-odoo:nbuntu
  image: xtremxpert/docker-odoo:8.0
  links:
  - db:db
  stdin_open: true
  volumes:
  - ./addons:/mnt/extra-addons
db:
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_PASSWORD: odoopass
    POSTGRES_USER: odoo
  tty: true
  image: postgres:9.6
  stdin_open: true
